name: minecraft2vrcraft
main: net.Markcreator.minecraft2vrcraft.Main
version: 1.0
api-version: 1.20.6
description: >
             minecraft2vrcraft, made by Markcreator.
commands:
  export:
	description: Main command.