package net.Markcreator.minecraft2vrcraft;

import org.apache.commons.lang3.ArrayUtils;

public class SupportedBlocks {

	public static int getBlockIndex(String block) {
		return ArrayUtils.indexOf(blocks, block);
	}

	public static String getBlockName(int id) {
		return blocks[id];
	}

	public static String[] blocks = { "air", "acacia_door_bottom", "acacia_door_top", "acacia_leaves", "acacia_planks",
			"acacia_sapling", "acacia_trapdoor", "activator_rail", "activator_rail_on", "allium", "amethyst_block",
			"amethyst_cluster", "andesite", "attached_melon_stem", "attached_pumpkin_stem", "azalea_leaves",
			"azalea_plant", "azure_bluet", "bamboo_door_bottom", "bamboo_door_top", "bamboo_fence", "bamboo_fence_gate",
			"bamboo_fence_gate_particle", "bamboo_fence_particle", "bamboo_large_leaves", "bamboo_mosaic",
			"bamboo_planks", "bamboo_singleleaf", "bamboo_small_leaves", "bamboo_stalk", "bamboo_trapdoor",
			"barrel_top_open", "beacon", "bedrock", "bee_nest_front", "bee_nest_front_honey", "beehive_end",
			"beehive_front", "beehive_front_honey", "beehive_side", "big_dripleaf_stem", "big_dripleaf_tip",
			"birch_door_bottom", "birch_door_top", "birch_leaves", "birch_planks", "birch_sapling", "birch_trapdoor",
			"black_candle", "black_candle_lit", "black_concrete", "black_concrete_powder", "black_glazed_terracotta",
			"black_shulker_box", "black_stained_glass", "black_stained_glass_pane_top", "black_terracotta",
			"black_wool", "blast_furnace_front", "blast_furnace_front_on", "blue_candle", "blue_candle_lit",
			"blue_concrete", "blue_concrete_powder", "blue_glazed_terracotta", "blue_ice", "blue_orchid",
			"blue_shulker_box", "blue_stained_glass", "blue_stained_glass_pane_top", "blue_terracotta", "blue_wool",
			"brain_coral", "brain_coral_block", "brain_coral_fan", "brewing_stand", "brewing_stand_base", "bricks",
			"brown_candle", "brown_candle_lit", "brown_concrete", "brown_concrete_powder", "brown_glazed_terracotta",
			"brown_mushroom", "brown_mushroom_block", "brown_shulker_box", "brown_stained_glass",
			"brown_stained_glass_pane_top", "brown_terracotta", "brown_wool", "bubble_coral", "bubble_coral_block",
			"bubble_coral_fan", "budding_amethyst", "cake_inner", "calcite", "calibrated_sculk_sensor_amethyst",
			"calibrated_sculk_sensor_input_side", "calibrated_sculk_sensor_top", "campfire_fire", "campfire_log",
			"campfire_log_lit", "candle", "candle_lit", "cartography_table_top", "carved_pumpkin", "cauldron_inner",
			"cave_vines", "cave_vines_lit", "cave_vines_plant", "cave_vines_plant_lit", "chain",
			"chain_command_block_back", "chain_command_block_conditional", "chain_command_block_front",
			"chain_command_block_side", "cherry_door_bottom", "cherry_door_top", "cherry_leaves", "cherry_planks",
			"cherry_sapling", "cherry_trapdoor", "chipped_anvil_top", "chiseled_bookshelf_empty",
			"chiseled_bookshelf_occupied", "chiseled_copper", "chiseled_deepslate", "chiseled_nether_bricks",
			"chiseled_polished_blackstone", "chiseled_red_sandstone", "chiseled_sandstone", "chiseled_stone_bricks",
			"chorus_flower", "chorus_flower_dead", "chorus_plant", "clay", "coal_block", "coal_ore", "coarse_dirt",
			"cobbled_deepslate", "cobblestone", "cobweb", "command_block_back", "command_block_conditional",
			"command_block_front", "command_block_side", "comparator", "comparator_on", "composter_compost",
			"composter_ready", "conduit", "copper_block", "copper_bulb", "copper_bulb_lit", "copper_bulb_lit_powered",
			"copper_bulb_powered", "copper_door_bottom", "copper_door_top", "copper_grate", "copper_ore",
			"copper_trapdoor", "cornflower", "cracked_deepslate_bricks", "cracked_deepslate_tiles",
			"cracked_nether_bricks", "cracked_polished_blackstone_bricks", "cracked_stone_bricks", "crafter_bottom",
			"crafter_east", "crafter_east_crafting", "crafter_east_triggered", "crafter_north",
			"crafter_north_crafting", "crafter_south", "crafter_south_triggered", "crafter_top", "crafter_top_crafting",
			"crafter_top_triggered", "crafter_west", "crafter_west_crafting", "crafter_west_triggered",
			"crafting_table_front", "crimson_door_bottom", "crimson_door_top", "crimson_fungus", "crimson_nylium",
			"crimson_nylium_side", "crimson_planks", "crimson_roots", "crimson_roots_pot", "crimson_trapdoor",
			"crying_obsidian", "cut_copper", "cut_red_sandstone", "cut_sandstone", "cyan_candle", "cyan_candle_lit",
			"cyan_concrete", "cyan_concrete_powder", "cyan_glazed_terracotta", "cyan_shulker_box", "cyan_stained_glass",
			"cyan_stained_glass_pane_top", "cyan_terracotta", "cyan_wool", "damaged_anvil_top", "dandelion",
			"dark_oak_door_bottom", "dark_oak_door_top", "dark_oak_leaves", "dark_oak_planks", "dark_oak_sapling",
			"dark_oak_trapdoor", "dark_prismarine", "daylight_detector_inverted_top", "dead_brain_coral",
			"dead_brain_coral_block", "dead_brain_coral_fan", "dead_bubble_coral", "dead_bubble_coral_block",
			"dead_bubble_coral_fan", "dead_bush", "dead_fire_coral", "dead_fire_coral_block", "dead_fire_coral_fan",
			"dead_horn_coral", "dead_horn_coral_block", "dead_horn_coral_fan", "dead_tube_coral",
			"dead_tube_coral_block", "dead_tube_coral_fan", "debug", "deepslate_bricks", "deepslate_coal_ore",
			"deepslate_copper_ore", "deepslate_diamond_ore", "deepslate_emerald_ore", "deepslate_gold_ore",
			"deepslate_iron_ore", "deepslate_lapis_ore", "deepslate_redstone_ore", "deepslate_tiles", "detector_rail",
			"detector_rail_on", "diamond_block", "diamond_ore", "diorite", "dirt", "dispenser_front",
			"dispenser_front_vertical", "dragon_egg", "dripstone_block", "dropper_front", "dropper_front_vertical",
			"emerald_block", "emerald_ore", "end_portal_frame_eye", "end_rod", "end_stone", "end_stone_bricks",
			"exposed_chiseled_copper", "exposed_copper", "exposed_copper_bulb", "exposed_copper_bulb_lit",
			"exposed_copper_bulb_lit_powered", "exposed_copper_bulb_powered", "exposed_copper_door_bottom",
			"exposed_copper_door_top", "exposed_copper_grate", "exposed_copper_trapdoor", "exposed_cut_copper",
			"farmland", "farmland_moist", "fern", "fire_coral", "fire_coral_block", "fire_coral_fan",
			"fletching_table_front", "flower_pot", "flowering_azalea_leaves", "frogspawn", "furnace_front",
			"furnace_front_on", "gilded_blackstone", "glass", "glass_pane_top", "glow_item_frame", "glow_lichen",
			"glowstone", "gold_block", "gold_ore", "granite", "grass_block_side_overlay", "gravel", "gray_candle",
			"gray_candle_lit", "gray_concrete", "gray_concrete_powder", "gray_glazed_terracotta", "gray_shulker_box",
			"gray_stained_glass", "gray_stained_glass_pane_top", "gray_terracotta", "gray_wool", "green_candle",
			"green_candle_lit", "green_concrete", "green_concrete_powder", "green_glazed_terracotta",
			"green_shulker_box", "green_stained_glass", "green_stained_glass_pane_top", "green_terracotta",
			"green_wool", "grindstone_pivot", "grindstone_round", "grindstone_side", "hanging_roots", "heavy_core",
			"honeycomb_block", "hopper_inside", "hopper_outside", "hopper_top", "horn_coral", "horn_coral_block",
			"horn_coral_fan", "ice", "iron_bars", "iron_block", "iron_door_bottom", "iron_door_top", "iron_ore",
			"iron_trapdoor", "item_frame", "jack_o_lantern", "jigsaw_lock", "jungle_door_bottom", "jungle_door_top",
			"jungle_leaves", "jungle_planks", "jungle_sapling", "jungle_trapdoor", "kelp", "kelp_plant", "ladder",
			"lantern", "lapis_block", "lapis_ore", "large_amethyst_bud", "large_fern_bottom", "large_fern_top",
			"lava_flow", "lava_still", "lectern_base", "lectern_front", "lectern_sides", "lectern_top", "lever",
			"light_blue_candle", "light_blue_candle_lit", "light_blue_concrete", "light_blue_concrete_powder",
			"light_blue_glazed_terracotta", "light_blue_shulker_box", "light_blue_stained_glass",
			"light_blue_stained_glass_pane_top", "light_blue_terracotta", "light_blue_wool", "light_gray_candle",
			"light_gray_candle_lit", "light_gray_concrete", "light_gray_concrete_powder",
			"light_gray_glazed_terracotta", "light_gray_shulker_box", "light_gray_stained_glass",
			"light_gray_stained_glass_pane_top", "light_gray_terracotta", "light_gray_wool", "lightning_rod",
			"lightning_rod_on", "lilac_bottom", "lilac_top", "lily_of_the_valley", "lily_pad", "lime_candle",
			"lime_candle_lit", "lime_concrete", "lime_concrete_powder", "lime_glazed_terracotta", "lime_shulker_box",
			"lime_stained_glass", "lime_stained_glass_pane_top", "lime_terracotta", "lime_wool", "loom_front",
			"magenta_candle", "magenta_candle_lit", "magenta_concrete", "magenta_concrete_powder",
			"magenta_glazed_terracotta", "magenta_shulker_box", "magenta_stained_glass",
			"magenta_stained_glass_pane_top", "magenta_terracotta", "magenta_wool", "magma", "mangrove_door_bottom",
			"mangrove_door_top", "mangrove_leaves", "mangrove_planks", "mangrove_propagule",
			"mangrove_propagule_hanging", "mangrove_trapdoor", "medium_amethyst_bud", "melon_stem", "moss_block",
			"mossy_cobblestone", "mossy_stone_bricks", "mud", "mud_bricks", "mushroom_block_inside", "mushroom_stem",
			"nether_bricks", "nether_gold_ore", "nether_portal", "nether_quartz_ore", "nether_sprouts",
			"nether_wart_block", "netherite_block", "netherrack", "note_block", "oak_door_bottom", "oak_door_top",
			"oak_leaves", "oak_planks", "oak_sapling", "oak_trapdoor", "observer_back", "observer_back_on",
			"observer_front", "obsidian", "orange_candle", "orange_candle_lit", "orange_concrete",
			"orange_concrete_powder", "orange_glazed_terracotta", "orange_shulker_box", "orange_stained_glass",
			"orange_stained_glass_pane_top", "orange_terracotta", "orange_tulip", "orange_wool", "oxeye_daisy",
			"oxidized_chiseled_copper", "oxidized_copper", "oxidized_copper_bulb", "oxidized_copper_bulb_lit",
			"oxidized_copper_bulb_lit_powered", "oxidized_copper_bulb_powered", "oxidized_copper_door_bottom",
			"oxidized_copper_door_top", "oxidized_copper_grate", "oxidized_copper_trapdoor", "oxidized_cut_copper",
			"packed_ice", "packed_image_1000", "packed_image_1001", "packed_image_1002", "packed_image_1003",
			"packed_image_1004", "packed_image_1005", "packed_image_1006", "packed_image_1007", "packed_image_1008",
			"packed_image_1009", "packed_image_1010", "packed_image_1011", "packed_image_1012", "packed_image_1013",
			"packed_image_1014", "packed_image_1015", "packed_image_1016", "packed_image_1017", "packed_image_1018",
			"packed_image_1019", "packed_image_1020", "packed_image_1021", "packed_image_1022", "packed_image_1023",
			"packed_image_936", "packed_image_937", "packed_image_938", "packed_image_939", "packed_image_940",
			"packed_image_941", "packed_image_942", "packed_image_943", "packed_image_944", "packed_image_945",
			"packed_image_946", "packed_image_947", "packed_image_948", "packed_image_949", "packed_image_950",
			"packed_image_951", "packed_image_952", "packed_image_953", "packed_image_954", "packed_image_955",
			"packed_image_956", "packed_image_957", "packed_image_958", "packed_image_959", "packed_image_960",
			"packed_image_961", "packed_image_962", "packed_image_963", "packed_image_964", "packed_image_965",
			"packed_image_966", "packed_image_967", "packed_image_968", "packed_image_969", "packed_image_970",
			"packed_image_971", "packed_image_972", "packed_image_973", "packed_image_974", "packed_image_975",
			"packed_image_976", "packed_image_977", "packed_image_978", "packed_image_979", "packed_image_980",
			"packed_image_981", "packed_image_982", "packed_image_983", "packed_image_984", "packed_image_985",
			"packed_image_986", "packed_image_987", "packed_image_988", "packed_image_989", "packed_image_990",
			"packed_image_991", "packed_image_992", "packed_image_993", "packed_image_994", "packed_image_995",
			"packed_image_996", "packed_image_997", "packed_image_998", "packed_image_999", "packed_mud",
			"peony_bottom", "peony_top", "pink_candle", "pink_candle_lit", "pink_concrete", "pink_concrete_powder",
			"pink_glazed_terracotta", "pink_petals", "pink_petals_stem", "pink_shulker_box", "pink_stained_glass",
			"pink_stained_glass_pane_top", "pink_terracotta", "pink_tulip", "pink_wool", "piston_inner",
			"piston_top_sticky", "pointed_dripstone_down_base", "pointed_dripstone_down_frustum",
			"pointed_dripstone_down_middle", "pointed_dripstone_down_tip", "pointed_dripstone_down_tip_merge",
			"pointed_dripstone_up_base", "pointed_dripstone_up_frustum", "pointed_dripstone_up_middle",
			"pointed_dripstone_up_tip", "pointed_dripstone_up_tip_merge", "polished_andesite", "polished_blackstone",
			"polished_blackstone_bricks", "polished_deepslate", "polished_diorite", "polished_granite", "polished_tuff",
			"poppy", "potted_azalea_bush_plant", "potted_flowering_azalea_bush_plant", "powder_snow", "powered_rail",
			"powered_rail_on", "prismarine", "prismarine_bricks", "pumpkin_stem", "purple_candle", "purple_candle_lit",
			"purple_concrete", "purple_concrete_powder", "purple_glazed_terracotta", "purple_shulker_box",
			"purple_stained_glass", "purple_stained_glass_pane_top", "purple_terracotta", "purple_wool", "purpur_block",
			"quartz_bricks", "rail", "rail_corner", "raw_copper_block", "raw_gold_block", "raw_iron_block",
			"red_candle", "red_candle_lit", "red_concrete", "red_concrete_powder", "red_glazed_terracotta",
			"red_mushroom", "red_mushroom_block", "red_nether_bricks", "red_sand", "red_shulker_box",
			"red_stained_glass", "red_stained_glass_pane_top", "red_terracotta", "red_tulip", "red_wool",
			"redstone_block", "redstone_dust_dot", "redstone_dust_overlay", "redstone_lamp", "redstone_lamp_on",
			"redstone_ore", "redstone_torch", "redstone_torch_off", "repeater", "repeater_on",
			"repeating_command_block_back", "repeating_command_block_conditional", "repeating_command_block_front",
			"repeating_command_block_side", "respawn_anchor_bottom", "respawn_anchor_top", "respawn_anchor_top_off",
			"rooted_dirt", "rose_bush_bottom", "rose_bush_top", "sand", "sculk", "sculk_catalyst_side_bloom",
			"sculk_catalyst_top_bloom", "sculk_sensor_tendril_active", "sculk_sensor_tendril_inactive",
			"sculk_shrieker_can_summon_inner_top", "sculk_shrieker_inner_top", "sculk_vein", "sea_lantern",
			"sea_pickle", "seagrass", "short_grass", "shroomlight", "shulker_box", "slime_block", "small_amethyst_bud",
			"small_dripleaf_stem_bottom", "small_dripleaf_stem_top", "smithing_table_front", "smoker_front",
			"smoker_front_on", "smooth_basalt", "smooth_stone", "smooth_stone_slab_side",
			"sniffer_egg_not_cracked_bottom", "sniffer_egg_not_cracked_east", "sniffer_egg_not_cracked_north",
			"sniffer_egg_not_cracked_south", "sniffer_egg_not_cracked_top", "sniffer_egg_not_cracked_west",
			"sniffer_egg_slightly_cracked_bottom", "sniffer_egg_slightly_cracked_east",
			"sniffer_egg_slightly_cracked_north", "sniffer_egg_slightly_cracked_south",
			"sniffer_egg_slightly_cracked_top", "sniffer_egg_slightly_cracked_west", "sniffer_egg_very_cracked_bottom",
			"sniffer_egg_very_cracked_east", "sniffer_egg_very_cracked_north", "sniffer_egg_very_cracked_south",
			"sniffer_egg_very_cracked_top", "sniffer_egg_very_cracked_west", "snow", "soul_campfire_fire",
			"soul_campfire_log_lit", "soul_lantern", "soul_sand", "soul_soil", "soul_torch", "spawner", "sponge",
			"spore_blossom", "spore_blossom_base", "spruce_door_bottom", "spruce_door_top", "spruce_leaves",
			"spruce_planks", "spruce_sapling", "spruce_trapdoor", "stone", "stone_bricks", "stonecutter_saw",
			"structure_block", "structure_block_corner", "structure_block_data", "structure_block_load",
			"structure_block_save", "sugar_cane", "sunflower_back", "sunflower_bottom", "sunflower_front",
			"sunflower_top", "tall_grass_bottom", "tall_grass_top", "tall_seagrass_bottom", "tall_seagrass_top",
			"terracotta", "tinted_glass", "torch", "torchflower", "trial_spawner_bottom", "trial_spawner_side_active",
			"trial_spawner_side_active_ominous", "trial_spawner_side_inactive", "trial_spawner_side_inactive_ominous",
			"trial_spawner_top_active", "trial_spawner_top_active_ominous", "trial_spawner_top_ejecting_reward",
			"trial_spawner_top_ejecting_reward_ominous", "trial_spawner_top_inactive",
			"trial_spawner_top_inactive_ominous", "tripwire", "tripwire_hook", "tube_coral", "tube_coral_block",
			"tube_coral_fan", "tuff", "tuff_bricks", "turtle_egg", "turtle_egg_slightly_cracked",
			"turtle_egg_very_cracked", "twisting_vines", "twisting_vines_plant", "vault_bottom", "vault_bottom_ominous",
			"vault_front_ejecting", "vault_front_ejecting_ominous", "vault_front_off", "vault_front_off_ominous",
			"vault_front_on", "vault_front_on_ominous", "vault_side_off", "vault_side_off_ominous", "vault_side_on",
			"vault_side_on_ominous", "vault_top", "vault_top_ejecting", "vault_top_ejecting_ominous",
			"vault_top_ominous", "vine", "warped_door_bottom", "warped_door_top", "warped_fungus", "warped_nylium",
			"warped_nylium_side", "warped_planks", "warped_roots", "warped_roots_pot", "warped_trapdoor",
			"warped_wart_block", "water_flow", "water_overlay", "water_still", "weathered_chiseled_copper",
			"weathered_copper", "weathered_copper_bulb", "weathered_copper_bulb_lit",
			"weathered_copper_bulb_lit_powered", "weathered_copper_bulb_powered", "weathered_copper_door_bottom",
			"weathered_copper_door_top", "weathered_copper_grate", "weathered_copper_trapdoor", "weathered_cut_copper",
			"weeping_vines", "weeping_vines_plant", "wet_sponge", "white_candle", "white_candle_lit", "white_concrete",
			"white_concrete_powder", "white_glazed_terracotta", "white_shulker_box", "white_stained_glass",
			"white_stained_glass_pane_top", "white_terracotta", "white_tulip", "white_wool", "wither_rose",
			"yellow_candle", "yellow_candle_lit", "yellow_concrete", "yellow_concrete_powder",
			"yellow_glazed_terracotta", "yellow_shulker_box", "yellow_stained_glass", "yellow_stained_glass_pane_top",
			"yellow_terracotta", "yellow_wool", "acacia_log", "ancient_debris", "anvil", "azalea", "bamboo_block",
			"barrel", "basalt", "bee_nest", "bell", "big_dripleaf", "birch_log", "blackstone", "blast_furnace",
			"bone_block", "cactus", "cake", "cauldron", "cherry_log", "chiseled_bookshelf", "chiseled_quartz_block",
			"chiseled_tuff_bricks", "chiseled_tuff", "composter", "crafting_table", "crimson_stem", "dark_oak_log",
			"daylight_detector", "deepslate", "dirt_path", "dried_kelp", "enchanting_table", "end_portal_frame",
			"fletching_table", "flowering_azalea", "furnace", "hay_block", "honey_block", "jigsaw", "jukebox",
			"jungle_log", "lodestone", "loom", "mangrove_log", "mangrove_roots", "melon", "muddy_mangrove_roots",
			"mycelium", "oak_log", "observer", "ochre_froglight", "pearlescent_froglight", "piston", "pitcher_crop",
			"podzol", "polished_basalt", "potted_azalea_bush", "potted_flowering_azalea_bush", "pumpkin",
			"purpur_pillar", "quartz_block", "quartz_pillar", "red_sandstone", "reinforced_deepslate", "sandstone",
			"scaffolding", "sculk_catalyst", "sculk_sensor", "sculk_shrieker", "small_dripleaf", "smithing_table",
			"smoker", "spruce_log", "stonecutter", "stripped_acacia_log", "stripped_bamboo_block", "stripped_birch_log",
			"stripped_cherry_log", "stripped_crimson_stem", "stripped_dark_oak_log", "stripped_jungle_log",
			"stripped_mangrove_log", "stripped_oak_log", "stripped_spruce_log", "stripped_warped_stem", "target", "tnt",
			"verdant_froglight", "warped_stem", "grass_block", "grass_block_snow", "bookshelf" };
}
